Do not try to publish test results/code coverage in fork
Uninett/zino pull request #242
Opened 2024-06-03 07:30 UTC by johannaengland

When doing #230 I remove the condition `github.repository_owner == 'Uninett'` because I thought that was given, but I forgot, that the workflow `Run test suite` will also be triggered by pushes to the master branch of a fork, which will in turn trigger the `Publish test and coverage results` workflow. This workflow will then run on the master branch of the fork. 
And both uploading test results and code coverage will fail since the fork does not have the correct permissions/the code coverage token. Failing workflows can be seen here for [publish test results](https://github.com/johannaengland/zino/actions/runs/9345474386/job/25718806440) and [publish code coverage](https://github.com/england-johanna/testing/actions/runs/9345772140/job/25719278459).

So we do need to restrict this workflow to only run on the Uninett repository.

2024-06-06 11:11 UTC, hmpf requested changes
Commit message: 

"Prevent publishing test results/code coverage in fork

This only works intermittently so cut down on the noise"

or something similar.

2024-06-06 11:12 UTC, hmpf commented
> Commit message:
> 
> "Prevent publishing test results/code coverage in fork
> 
> This only works intermittently so cut down on the noise"
> 
> or something similar.

.. or passive-aggressively mention something something about codecov behaving badly =)

2024-06-06 11:15 UTC, johannaengland commented
> Commit message:
> 
> "Prevent publishing test results/code coverage in fork
> 
> This only works intermittently so cut down on the noise"
> 
> or something similar.

But publishing test results/code coverage in fork never work, it is not a problem that is fail once in a while, it always fails, because it lacks the necessary permissions

But I can make the commit message a bit more detailed

2024-06-06 11:15 UTC, hmpf commented
"Avoid bothering codecov with code in forks

Codecov does not like forks."

Short, sweet, to the point and suitably #%&/(&%/(.

2024-06-07 07:41 UTC, lunkwill42 commented
> "Avoid bothering codecov with code in forks
> 
> Codecov does not like forks."
> 
> Short, sweet, to the point and suitably #%&/(&%/(.

You guys are discussing and confusing two very different issues here:

1. Workflows that run in the upstream repo.
2. Workflows that run in a forked repo.


The issue with no. 1 is when a workflow is triggered by a PR from a forked repo. The workflow runs in the upstream repo, but in the context of the fork (so that things like upstream repo secrets are not available to the workflow).  CodeCov supports tokenless uploads for public upstream repos, so the secret isn't needed.  However, CodeCov also enforces rate limits for tokenless uploads, and GitHub has *many* anonymous requests all over for this API, so it becomes a problem for us.


The issue with no 2. is just when you push code to your forked repo, regardless of whether this is associated with a PR in an upstream repo or not: You likely did not configure CodeCov to accept data from the forked repo, so it's never going to work (unless you log in to CodeCov and explicitly add your forked repo as well).


It sounds to me like @johannaengland is discussing no. 2, while @hmpf is annoyed about no. 1.

2024-06-12 11:41 UTC, hmpf approved these changes
Remember to fit the first line of the commit message to the "This commit will.." pattern, easily done by squashing from github itself.

2024-06-12 12:38 UTC, merged