Add support for subcommands in the API
Uninett/zino pull request #254
Opened 2024-06-13 07:55 UTC by stveit

Work for #101

2024-06-13 08:17 UTC, hmpf reviewed
Fine start, now you "just" need to update the tests :)

2024-06-14 09:42 UTC, johannaengland approved these changes

2024-06-21 14:06 UTC, lunkwill42 requested changes
While it's a fine attempt, I feel like this just complicates future maintenance.  

Specifically, I'm not comfortable with having to explicitly add new methods to a an extra config tuple, located potentially far away from the implementation itself, to mark them as special.  Marking these functions using a decorator would be nicer.

However, at this point, I might suggest two different approaches:

1. Add more magic to the dispatcher code so it finds valid commands from method names, automatically understanding `do_x_y()` as an implementation of the command `X Y` while `do_x()` is a different command.

2. Or, toss the magic stuff I wrote earlier and switch to a scheme involving explicit routing of commands using decorators.  Think similarly to flask routes, e.g.
   ```python
   @route("PM")
   def do_pm(self):
       ...

   @route("PM ADD")
   def do_pm_add(self, arg1, arg2):
       ...
   ```

I would pair on something this, if desirable :)

2024-07-01 11:21 UTC, stveit commented
#247 is used instead

2024-07-01 11:21 UTC, closed without merging