Customize logging of various SNMP traps just as Zino 1 does
Uninett/zino pull request #320
Opened 2024-07-18 11:52 UTC by lunkwill42

## Scope and purpose

Fixes #319

### This pull request
* adds multiple trap observers to the `logged_traps` module, one for each MIB mentioned in #319

## Contributor Checklist

Every pull request should have this checklist filled out, no matter how small it is.
More information about contributing to Zino can be found in the
[README](https://github.com/Uninett/zino/blob/master/README.md#developing-zino).

* [ ] Added a changelog fragment for [towncrier](https://github.com/Uninett/zino/blob/master/README.md#before-merging-a-pull-request)
* [ ] Added/amended tests for new/changed code 
* [ ] Added/changed documentation
* [ ] Linted/formatted the code with black, ruff and isort, easiest by using [pre-commit](https://github.com/Uninett/zino/blob/master/README.md#code-style)
* [ ] The first line of the commit message continues the sentence "If applied, this commit will ...", starts with a capital letter, does not end with punctuation and is 50 characters or less long. See https://cbea.ms/git-commit/
* [ ] If applicable: Created new issues if this PR does not fix the issue completely/there is further work to be done

2024-07-24 06:59 UTC, johannaengland requested changes

2024-08-19 12:55 UTC, lunkwill42 commented on src/zino/trapobservers/logged_traps.py
> +            "%s: PIM-invalid-%s: from %s group %s RP %s",
There is no requirement to have bit-for-bit identical logging.  In reality, the only requirement is providing a backward-compatible API :)

2024-08-19 13:08 UTC, lunkwill42 commented on tests/trapobservers/logged_traps_test.py
> +class TestCiscoPimTrapLogger:
Not really, no. There is only a single difference between them, and that is a single word of the logged message.

At best, the tests could be parametrized to take the trap name as input, but the coverage is already in place.

2024-08-19 13:20 UTC, johannaengland approved these changes

2024-08-20 10:33 UTC, merged