Set up documentation on read the docs
Uninett/zino pull request #372
Opened 2024-09-13 12:20 UTC by hmpf

## Scope and purpose

Secures the zino namespace on read the docs.

## Contributor Checklist

Every pull request should have this checklist filled out, no matter how small it is.
More information about contributing to Zino can be found in the
[README](https://github.com/Uninett/zino/blob/master/README.md#developing-zino).

* [X] Added a changelog fragment for [towncrier](https://github.com/Uninett/zino/blob/master/README.md#before-merging-a-pull-request)
* [ ] Added/amended tests for new/changed code 

There are no code changes, hence no tests.

* [X] Added/changed documentation
* [ ] Linted/formatted the code with black, ruff and isort, easiest by using [pre-commit](https://github.com/Uninett/zino/blob/master/README.md#code-style)

There are no code changes, hence no linting.

* [X] The first line of the commit message continues the sentence "If applied, this commit will ...", starts with a capital letter, does not end with punctuation and is 50 characters or less long. See https://cbea.ms/git-commit/
* [ ] If applicable: Created new issues if this PR does not fix the issue completely/there is further work to be done

2024-09-13 12:22 UTC, hmpf commented
Black complains about "docs/conf.py" which is autogenerated.

2024-09-18 05:09 UTC, johannaengland approved these changes

2024-09-18 05:09 UTC, johannaengland commented on changelog.d/+add-docs-dir.added.md
> +the name "zino" there.
```suggestion
Added directory for sphinx docs in order to set up read the docs and secure
the name "zino" there.
```

2024-09-18 06:19 UTC, lunkwill42 requested changes
Looks decent, just nitpicking details :)

2024-09-18 06:19 UTC, lunkwill42 commented on .readthedocs.yaml
> +    python: "3.12"
Zino itself will not currently run on Python 3.12 (some of its dependencies won't import).  Although the docs are currently empty, if we wish to auto-import some of the modules during doc generation, we should do so on a Python version that Zino supports (i.e. 3.11, for now).

```suggestion
    python: "3.11"
```

2024-09-18 06:19 UTC, lunkwill42 commented on docs/conf.py
> +copyright = '2024, Morten Brekkevold, Johanna England, Simon Tveit'
We cannot claim personal copyright here :-)

Either

```suggestion
copyright = '2024, Sikt'
```

or 


```suggestion
copyright = '2024, Sikt - The Norwegian Agency for Shared Services in Education and Research'
```

2024-09-23 08:48 UTC, lunkwill42 approved these changes

2024-09-23 08:49 UTC, merged