Implement getnext capable of multi-var query
Uninett/zino pull request #80
Opened 2023-10-05 09:58 UTC by lunkwill42

This adds an alternative getnext implementation (getnext2), which is capable of dispatching multi-varbind queries, and capable of translating the response varbinds to symbolic names.

2023-10-05 09:59 UTC, lunkwill42 commented
I haven't checked out #76 yet, so this might be in conflict with that...

2023-10-06 08:12 UTC, lunkwill42 commented
> I haven't checked out #76 yet, so this might be in conflict with that...

I've rebased this on #76, so until that is merged, I've changed this PR into a draft

2023-10-12 07:32 UTC, stveit requested changes
smol things

2023-10-12 07:32 UTC, stveit commented on src/zino/snmp.py
> +        :return: A sequence of ObjectTypes representing the resulting MIB variables, or None if nothing could be found
```suggestion
        :return: A sequence of ObjectTypes representing the resulting MIB variables
```

2023-10-12 07:32 UTC, stveit commented on src/zino/snmp.py
> +                 be found
```suggestion
        :return: A sequence of MibObject instances representing the resulting MIB variables
```

2023-10-12 07:32 UTC, stveit commented on tests/snmp_test.py
> +        assert any(k == Identifier("IF-MIB", "ifAlias", OID(".2")) for k, v in response)
Was a bit unsure what k and v was reading this. I assumed key and value, implying a dictionary, but that aint right.
Might be clearer to write like this:
```suggestion
        assert any(identifier == Identifier("IF-MIB", "ifName", OID(".2")) for identifier, _ in response)
        assert any(identifier == Identifier("IF-MIB", "ifAlias", OID(".2")) for identifier, _ in response)
```

2023-10-12 07:56 UTC, stveit approved these changes

2023-10-12 08:06 UTC, merged